run:
  # timeout defines the linter timeout. Default: 1m
  timeout: 5m

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 30
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 10.0

  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 100
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: 50

linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - goerr113
    - golint
    - gomnd
    - gomoddirectives
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - varcheck
    - varnamelen
    - wastedassign
    - gochecknoglobals

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - testpackage
